name: eventhub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  google_sign_in: ^7.2.0

  # State management
  flutter_riverpod: ^3.3.2

  # Icons
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration pour générer le logo de l'application
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoev.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logoev.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoev.png
    - assets/images/logoblanc.png
    - assets/images/tech.jpg
    - assets/images/music.jpg
    - assets/images/user_avatar.jpg