// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHXChbD1xYXawt3EG8QNWZjVoM65xyW-4',
    appId: '1:930281380072:web:25189f1d00440ad479115d',
    messagingSenderId: '930281380072',
    projectId: 'eventhub-d411f',
    authDomain: 'eventhub-d411f.firebaseapp.com',
    storageBucket: 'eventhub-d411f.firebasestorage.app',
    measurementId: 'G-D70N1QGLW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAocb8EDI81nMmSgcVwM8vkY62Figkc6Nk',
    appId: '1:930281380072:android:cb45cb9366f6617e79115d',
    messagingSenderId: '930281380072',
    projectId: 'eventhub-d411f',
    storageBucket: 'eventhub-d411f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9mK-uC2xdOuK_-syti49l8xtVZsg3ICc',
    appId: '1:930281380072:ios:6f111a2562693a8179115d',
    messagingSenderId: '930281380072',
    projectId: 'eventhub-d411f',
    storageBucket: 'eventhub-d411f.firebasestorage.app',
    iosClientId: '930281380072-i20pglc1crsues71usoe3gs14a4fvvic.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9mK-uC2xdOuK_-syti49l8xtVZsg3ICc',
    appId: '1:930281380072:ios:6f111a2562693a8179115d',
    messagingSenderId: '930281380072',
    projectId: 'eventhub-d411f',
    storageBucket: 'eventhub-d411f.firebasestorage.app',
    iosClientId: '930281380072-i20pglc1crsues71usoe3gs14a4fvvic.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHXChbD1xYXawt3EG8QNWZjVoM65xyW-4',
    appId: '1:930281380072:web:b83b0e6adc87e6dc79115d',
    messagingSenderId: '930281380072',
    projectId: 'eventhub-d411f',
    authDomain: 'eventhub-d411f.firebaseapp.com',
    storageBucket: 'eventhub-d411f.firebasestorage.app',
    measurementId: 'G-YTK6BG8GVW',
  );
}
